#!/usr/bin/env python3
"""Generate standalone/nycesolutionssafrica-refactored.html from the repository sources.

The standalone file is the same application as index.html with the stylesheet,
configuration, catalogue, application code and images inlined, so it opens from a
file:// URL with no server. Run this after editing any file under assets/ so the two
versions never drift apart:

    python3 tools/build-standalone.py

Only the Python standard library is used.
"""
import base64, mimetypes, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'standalone' / 'nycesolutionssafrica-refactored.html'

def read(rel):
    return (ROOT / rel).read_text(encoding='utf-8')

def data_uri(rel):
    path = ROOT / rel
    mime = mimetypes.guess_type(path.name)[0] or 'application/octet-stream'
    if path.suffix == '.webp':
        mime = 'image/webp'
    if path.suffix == '.svg':
        mime = 'image/svg+xml'
    return f"data:{mime};base64,{base64.b64encode(path.read_bytes()).decode('ascii')}"

def main():
    html = read('index.html')
    css = read('assets/css/styles.css')
    config = read('assets/js/config.js').replace('build: "repository"', 'build: "standalone"')
    catalogue = read('assets/js/catalogue.js')
    app = read('assets/js/app.js')
    assets = {k: data_uri(f'assets/images/{f}') for k, f in [('logo', 'logo.webp'), ('equipment', 'equipment.webp'), ('placeholder', 'placeholder.svg')]}

    # Inline the stylesheet.
    html, n = re.subn(r'<link rel="stylesheet" href="assets/css/styles.css">', lambda m: f'<style>\n{css}\n</style>', html)
    assert n == 1, 'stylesheet link not found'
    html = html.replace('<link rel="icon" href="assets/images/logo.webp" type="image/webp">', f'<link rel="icon" href="{assets["logo"]}" type="image/webp">')

    # Replace the asset map and the three external scripts with inlined code.
    asset_block = ('<script id="asset-map">\nwindow.NYCE_ASSETS = { logo: "' + assets['logo'] + '", equipment: "' + assets['equipment']
                   + '", placeholder: "' + assets['placeholder'] + '" };\n</script>')
    html, n = re.subn(r'<script id="asset-map">.*?</script>', lambda m: asset_block, html, flags=re.S)
    assert n == 1, 'asset map block not found'
    html, n = re.subn(r'<!-- Asset paths are relative.*?-->\s*', '<!-- Standalone build: generated by tools/build-standalone.py from the repository sources. Do not edit by hand. -->\n', html, flags=re.S)
    inline_scripts = f'<script>\n{config}\n</script>\n<script>\n{catalogue}\n</script>\n<script>\n{app}\n</script>'
    html, n = re.subn(r'<script src="assets/js/config.js"></script>\s*<script src="assets/js/catalogue.js"></script>\s*<script src="assets/js/app.js"></script>', lambda m: inline_scripts, html)
    assert n == 1, 'script tags not found'

    leftovers = re.findall(r'(?:src|href)="assets/', html)
    assert not leftovers, f'unresolved relative asset references: {leftovers}'
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html, encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size:,} bytes)')

if __name__ == '__main__':
    sys.exit(main())
